### ISSUE TITLE
Update to v11

### ISSUE THREAD

**Issue by kroese** [lncm/docker-clightning#6]
Can this container be updated to v11.1 if its not too much work for you? Would appreciate it!

**Comment by jaonoctus** [comment]
+1 for updating it.

---

I built [v22.11](https://hub.docker.com/r/jaonoctus/cln/tags) for myself.

```
jaonoctus/cln:v22.11@sha256:f466829730cd46a0d87f0ac367cbb60643d03c669bd5a78f2d1ed178295b57e8
```
